remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
title: Mathartist17's homepage
description: Bookmark this to keep an eye on my project updates!

# Site Settings
locale: "en-US"
title: "mathartist17 Blog"
url: "https://github.io"
baseurl: "" # Leave empty if your site is at the root domain

# Defaults for layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
